"""Execution quotidienne du paper trading G2 (3 enveloppes de 5 000 $ en parallele : vol 19 %, 25 %, 40 %).

Chaque jour a 00:10 UTC, apres la cloture quotidienne :
  1. clotures Binance ; aucun ordre si elles sont perimees ;
  2. limites de risque par enveloppe (kill switch, perte du jour, sans levier) ;
  3. decision (meme fonction que le backtest), un ordre par enveloppe sur Alpaca paper ;
  4. ordre > 5 000 $ : issue GitHub, execute seulement apres le label `approved` ;
  5. etat, journal et email (ordres, alertes ; resume chaque lundi).
Remettre une enveloppe en route apres un kill switch : passer `halted` a false dans paper_g2/state.json.
"""
import csv
import json
import logging
import os
import smtplib
import sys
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import pandas as pd
import requests

from btc_forecast.data import fetch_btc
from bot import g2_live as L

log = logging.getLogger(__name__)
DIR = Path(__file__).parent.parent / 'paper_g2'
EMAIL_FROM, EMAIL_TO = 'david.bucciero.ide@gmail.com', 'david.bucciero@outlook.fr'


def load_state():
    p = DIR / 'state.json'
    if p.exists():
        return json.loads(p.read_text())
    return {'start': None, 'last_date': None, 'sleeves': {n: L.new_sleeve() for n in L.SLEEVES}}


def save_state(st):
    DIR.mkdir(exist_ok=True)
    (DIR / 'state.json').write_text(json.dumps(st, indent=1))


def append(name, row):
    DIR.mkdir(parents=True, exist_ok=True)
    p = DIR / name
    new = not p.exists()
    with open(p, 'a', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(row))
        if new:
            w.writeheader()
        w.writerow(row)


class GitHub:
    def __init__(self):
        self.repo, self.token = os.environ.get('GITHUB_REPOSITORY'), os.environ.get('GITHUB_TOKEN')
        self.h = {'Authorization': f'Bearer {self.token}', 'Accept': 'application/vnd.github+json'}

    def _url(self, path):
        return f'https://api.github.com/repos/{self.repo}{path}'

    def approved(self, sleeve, symbol):
        if not self.token:
            return None
        r = requests.get(self._url('/issues'), headers=self.h, params={'labels': 'approved', 'state': 'open'}, timeout=30)
        for i in r.json() if r.ok else []:
            if i['title'].startswith(f'Validation ordre {sleeve} {symbol}'):
                return i['number']
        return None

    def already_asked(self, sleeve, symbol):
        r = requests.get(self._url('/issues'), headers=self.h, params={'state': 'open'}, timeout=30)
        return any(i['title'].startswith(f'Validation ordre {sleeve} {symbol}') for i in (r.json() if r.ok else []))

    def ask(self, sleeve, symbol, qty, price):
        if not self.token or self.already_asked(sleeve, symbol):
            return
        requests.post(self._url('/labels'), headers=self.h, json={'name': 'approved', 'color': '0e8a16'}, timeout=30)
        side = 'ACHAT' if qty > 0 else 'VENTE'
        body = (f'{side} de {abs(qty):.6f} {symbol} (~{abs(qty) * price:,.0f} $), au-dessus du seuil de '
                f'{L.APPROVAL_USD:,.0f} $.\n\nAjoute le label `approved` pour que le bot l\'execute a sa prochaine '
                'execution (00:10 UTC). Ferme l\'issue pour refuser.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_')
        requests.post(self._url('/issues'), headers=self.h, timeout=30,
                      json={'title': f'Validation ordre {sleeve} {symbol} ({side}, ~{abs(qty) * price:,.0f} $)', 'body': body})

    def close(self, number):
        requests.patch(self._url(f'/issues/{number}'), headers=self.h, json={'state': 'closed'}, timeout=30)


def send_email(subject, body, attachment=None):
    pwd = os.environ.get('EMAIL_PASSWORD')
    if not pwd:
        log.warning('EMAIL_PASSWORD absent : email ignore')
        return
    msg = MIMEMultipart()
    msg.attach(MIMEText(body, 'plain', 'utf-8'))
    if attachment and Path(attachment).exists():  # tableau de bord : ouvrir dans un navigateur
        part = MIMEApplication(Path(attachment).read_bytes(), Name='suivi_g2.html')
        part['Content-Disposition'] = 'attachment; filename="suivi_g2.html"'
        msg.attach(part)
    msg['Subject'], msg['From'], msg['To'] = subject, EMAIL_FROM, EMAIL_TO
    with smtplib.SMTP('smtp.gmail.com', 587) as s:
        s.starttls()
        s.login(EMAIL_FROM, pwd)
        s.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())


def run(broker, github, now=None):
    now = now or pd.Timestamp.now(tz='UTC')
    st = load_state()
    daily = pd.DataFrame({s: fetch_btc('1d', bars=400, symbol=s)['close'] for s in L.SYMBOLS})
    L.check_fresh(daily, now)
    if not L.realized_vol_ok(daily):
        raise RuntimeError('Donnees incompletes sur 30 jours : aucun ordre')
    day = f'{daily.index[-1] + pd.Timedelta(days=1):%Y-%m-%d}'
    if st['last_date'] == day:
        log.info(f'{day} deja traite')
        return st, []
    prices = daily.iloc[-1].to_dict()
    held = broker.positions()
    lines = []
    if st['start'] is None:
        # Premier demarrage : le compte ne doit detenir aucune crypto inconnue des enveloppes (ex. un ordre
        # passe lors d'une execution interrompue). On les revend pour partir de zero.
        for sym, pair in L.SYMBOLS.items():
            q = held.get(sym.replace('USDT', 'USD'), 0.0)
            if q > 0:
                fill = broker.market(pair, -q)
                lines.append(f"Initialisation : vente de {q:.6f} {sym.replace('USDT', '')} non suivi ({fill['status']})")
                append('ordres.csv', {'date': day, 'enveloppe': 'init', 'symbole': sym, 'quantite': -q,
                                      'prix': fill.get('price'), 'id': fill.get('id')})
                held[sym.replace('USDT', 'USD')] = 0.0
        st['start'] = day
        save_state(st)
    orders, events = L.plan_orders(st, daily, prices)
    lines += [f'{n} : {why}' for n, why in events]
    for name, sym, qty in orders:
        price, key = prices[sym], sym.replace('USDT', 'USD')
        if qty < 0:  # jamais vendre plus que la position reelle
            qty = max(qty, -held.get(key, 0.0))
            if qty == 0:
                continue
        if L.needs_approval(qty, price):
            num = github.approved(name, sym)
            if num is None:
                github.ask(name, sym, qty, price)
                lines.append(f'{name} {sym} : ordre de {qty * price:+,.0f} $ en attente de validation (issue GitHub)')
                continue
            github.close(num)
        fill = broker.market(L.SYMBOLS[sym], qty)
        if fill['status'] != 'filled' or not fill['filled_qty']:
            lines.append(f"{name} {sym} : ordre {fill['status']} ({fill.get('id')})")
            continue
        L.apply_fill(st['sleeves'][name], sym, fill['filled_qty'], fill['price'])
        held[key] = held.get(key, 0.0) + fill['filled_qty'] * ((1 - L.FEE) if fill['filled_qty'] > 0 else 1)
        lines.append(f"{name} {sym} : {fill['filled_qty']:+.6f} a {fill['price']:,.2f} $")
        append('ordres.csv', {'date': day, 'enveloppe': name, 'symbole': sym, 'quantite': fill['filled_qty'],
                              'prix': fill['price'], 'id': fill['id']})
        save_state(st)  # apres chaque ordre : une relance ne peut pas racheter en double
    for name in L.SLEEVES:
        sl = st['sleeves'][name]
        eq = L.equity(sl, prices)
        sl['prev_equity'] = eq
        w = L.decide(daily, L.SLEEVES[name]['target_vol'])
        append('journal.csv', {'date': day, 'enveloppe': name, 'valeur': round(eq, 2),
                               'drawdown': round(eq / sl['peak'] - 1, 4), 'arretee': sl['halted'],
                               **{f'poids_{s}': round(float(w[s]), 4) for s in L.SYMBOLS}})
    st['start'] = st['start'] or day
    st['last_date'] = day
    save_state(st)
    return st, lines


def main():
    logging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')
    broker = L.AlpacaPaper(os.environ['ALPACA_API_KEY'], os.environ['ALPACA_SECRET_KEY'])
    try:
        st, lines = run(broker, GitHub())
    except Exception as e:
        send_email('G2 paper : ERREUR, aucun ordre passe', f'{type(e).__name__}: {e}')
        raise
    from bot.dashboard_g2 import build
    daily = pd.DataFrame({s: fetch_btc('1d', bars=800, symbol=s)['close'] for s in L.SYMBOLS})
    try:
        dash = build(daily)
    except Exception as e:  # le tableau de bord ne doit jamais bloquer le trading
        log.warning(f'Tableau de bord non genere : {e}')
        dash = None
    prices = daily.iloc[-1].to_dict()
    summary = '\n'.join(f"{n} : {L.equity(sl, prices):,.0f} $ (pic {sl['peak']:,.0f} $){' ARRETEE' if sl['halted'] else ''}"
                        for n, sl in st['sleeves'].items())
    if lines or pd.Timestamp.now(tz='UTC').dayofweek == 0:
        send_email(f"G2 paper {st['last_date']}", '\n'.join(lines or ['Aucun ordre.']) + '\n\n' + summary
                   + '\n\nTableau de bord en piece jointe (ouvrir dans un navigateur).', attachment=dash)
    print('\n'.join(lines), '\n', summary)


if __name__ == '__main__':
    sys.exit(main())
